resource "aws_iam_role" "administration" {
  count = local.administration == null ? 0 : 1

  name               = local.administration.name
  description        = "CloudFormation StackSets administration role: assumed by CloudFormation to reach the execution role ${local.administration.execution_role_name} in target accounts."
  assume_role_policy = local.administration_assume_role_policy

  tags = local.tags
}

resource "aws_iam_role_policy" "administration" {
  count = local.administration == null ? 0 : 1

  # Same policy name as AWS's sample template.
  name   = "AssumeRole-${local.administration.execution_role_name}"
  role   = aws_iam_role.administration[0].id
  policy = local.administration_policy
}

resource "aws_iam_role" "execution" {
  count = local.execution == null ? 0 : 1

  name               = local.execution.name
  description        = "CloudFormation StackSets execution role: assumed by the StackSets administration role to deploy stack instances in this account."
  assume_role_policy = local.execution_assume_role_policy

  tags = local.tags
}

resource "aws_iam_role_policy" "execution_cloudformation" {
  #checkov:skip=CKV_AWS_355:cloudformation:* on * is the minimum AWS documents for a StackSets execution role; instance stack names are generated by StackSets.
  #checkov:skip=CKV_AWS_290:Same statement; StackSets needs to create, update, and delete the instance stack.
  #checkov:skip=CKV_AWS_289:Same statement; StackSets needs to create, update, and delete the instance stack.
  count = local.execution == null ? 0 : 1

  name   = "StackSetsCloudFormation"
  role   = aws_iam_role.execution[0].id
  policy = local.execution_cloudformation_policy
}

resource "aws_iam_role_policy" "execution_template" {
  count = try(local.execution.inline_policy, null) == null ? 0 : 1

  name   = "StackSetsTemplate"
  role   = aws_iam_role.execution[0].id
  policy = local.execution.inline_policy
}

resource "aws_iam_role_policy_attachment" "execution" {
  for_each = local.execution == null ? {} : local.execution.policy_arns

  role       = aws_iam_role.execution[0].name
  policy_arn = each.value
}
